// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdqorTsZgJBLplzPAG4TzZwZtnXKjAXiY',
    appId: '1:439816533161:web:1ba1e174b7d8a06125a5b8',
    messagingSenderId: '439816533161',
    projectId: 's-rocsks-asng',
    authDomain: 'fir-rocsks-asng.firebaseapp.com',
    storageBucket: 's-rocsks-asng.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBv3E8zpVr9y0MyzDrO9TR0UqQ36wdB4cs',
    appId: '1:439816533161:android:ab2ff58791b5a72e25a5b8',
    messagingSenderId: '439816533161',
    projectId: 's-rocsks-asng',
    storageBucket: 's-rocsks-asng.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBJGWNTZmEfuxixQtbZsg77FdljHAh2v4',
    appId: '1:439816533161:ios:57082e58bc150b0a25a5b8',
    messagingSenderId: '439816533161',
    projectId: 's-rocsks-asng',
    storageBucket: 's-rocsks-asng.firebasestorage.app',
    iosBundleId: 'com.example.sRocksAssignmentProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBJGWNTZmEfuxixQtbZsg77FdljHAh2v4',
    appId: '1:439816533161:ios:57082e58bc150b0a25a5b8',
    messagingSenderId: '439816533161',
    projectId: 's-rocsks-asng',
    storageBucket: 's-rocsks-asng.firebasestorage.app',
    iosBundleId: 'com.example.sRocksAssignmentProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdqorTsZgJBLplzPAG4TzZwZtnXKjAXiY',
    appId: '1:439816533161:web:d05af7c538e4889225a5b8',
    messagingSenderId: '439816533161',
    projectId: 's-rocsks-asng',
    authDomain: 'fir-rocsks-asng.firebaseapp.com',
    storageBucket: 's-rocsks-asng.firebasestorage.app',
  );
}
